site_name: modb
theme:
  name: material
  palette:
    primary: white
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
nav:
    - Home: index.html
    - Quickstart: Quickstart.md
    - FAQ: FAQ.md
    - Api: Api.md

  